name: 'magnussuther.chrome_extension_saml_decoder'
version: 1.0.1
description: 'A Chrome extension to decode and view SAML messages.'
author: 'Magnus Suther <magnus.suther@gmail.com>'
homepage: 'https://github.com/magnussuther/chrome-extension-saml-decoder'

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  w_flux: "^2.0.0"
  react: "^0.8.7"
  xml: "^2.3.2"
  chrome: "^0.7.0-dev1"
  bootstrap: "^3.3.4"
  mdl: "^1.5.2"
  di: "^3.3.4"
  pub_jquery:
    git: "git://github.com/magnussuther/pub_jquery_2.1.4"

dev_dependencies:
  test: "^0.12.3+8"
  path: "^1.3.6"

transformers:
  - di
  - $dart2js:
      csp: true
      commandLineOptions: [--enable-experimental-mirrors]